// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommentID int64          `gorm:"column:comment_id;not null" json:"comment_id"`
	Content   string         `gorm:"column:content;not null" json:"content"`
	PostID    int64          `gorm:"column:post_id;not null" json:"post_id"`
	AuthorID  int64          `gorm:"column:author_id;not null" json:"author_id"`
	ParentID  int64          `gorm:"column:parent_id;not null" json:"parent_id"`
	Status    int32          `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
